version: 1.0.{build}
image: Visual Studio 2017
install:
- ps: |
    Register-PSRepository -Name nuget.vigem.org -SourceLocation https://nuget.vigem.org/ -InstallationPolicy Trusted
build_script:
- ps: .\build.ps1 -configuration release
artifacts:
- path: bin
  name: Shibari
deploy:
- provider: Environment
  name: BUILDBOT
